# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using absolute file paths (relative paths do not work well with some
# of the snakemake tools we are using in the pipeline, such as shadow directories).
data:

  # Input table that lists all samples with their units and fastq files.
  # Paths in the table need to be absolute! No relative paths (e.g., `../data`)!
  samples: "phillips_samples.tsv"

  reference:

    # Path to the reference genome, using the file ideally as it is provided by the GATK bundle.
    # Path needs to be absolute! No relative path (e.g., `../ref`)!
    genome: "/global/scratch/projects/fc_moilab/projects/aspen/genome/CAM1604/Populus_tremuloides_var_CAM1604-4_HAP1_V2_release/Populus_tremuloides_var_CAM1604-4/sequences/Populus_tremuloides_var_CAM1604-4_HAP1.mainGenome.fasta"

# =================================================================================================
#    Snakemake settings
# =================================================================================================

max-jobs-per-second: 1
max-status-checks-per-second: 10
#local-cores: 1
latency-wait: 120

# Additional settings used for our purposes
use-conda: True
jobs: 60
max-jobs-per-timespan: "60/1m"
keep-going: True
rerun-incomplete: True
printshellcmds: True


# =================================================================================================
#     Default Resources
# =================================================================================================
default-resources:
  slurm_partition: "savio4_htc" 
  slurm_account:  "fc_moilab"
  runtime: 300
  cores: 1
  cpus_per_task: 1
  mem_mb: 9600

# =================================================================================================
#     Tool Parameters
# =================================================================================================

set-resources:

  # ----------------------------------------------------------------------
  #     fastp
  # ----------------------------------------------------------------------
  fastqc:
     threads: 4
     runtime: 420
        
  # ----------------------------------------------------------------------
  #     fastp
  # ----------------------------------------------------------------------

  fastp:
    threads: 4
    runtime: 240

  # ----------------------------------------------------------------------
  #     bwa-mem2
  # ----------------------------------------------------------------------

  bwa_prep:
    threads: 9
    mem_mb: 80000

  # ----------------------------------------------------------------------
  #     bwa_map
  # ----------------------------------------------------------------------

  # Just under three days to map for most files, some require longer.
  # savio4_htc is 9.14 GB per core
  bwa_map:
    cpus_per_task: 10
    runtime: 1440
    mem_mb: 73000
    slurm_partition: "savio4_htc"
    

  # ----------------------------------------------------------------------
  #     samtools_sort
  # ----------------------------------------------------------------------

  samtools_sort:
    mem_mb: 9600
    threads: 1
    runtime: 300

  # ----------------------------------------------------------------------
  #     mark_dups
  # ----------------------------------------------------------------------

  mark_dups:
    mem_mb: 19200
    threads: 2
    runtime: 420

  # ----------------------------------------------------------------------
  #     bamqc
  # ----------------------------------------------------------------------

  bamqc:
    mem_mb: 38400
    threads: 4
    runtime: 120

  # ----------------------------------------------------------------------
  #     mapDamage
  # ----------------------------------------------------------------------

  mapdamage:
    mem_mb: 24000
    threads: 3
    runtime: 2880


  # ----------------------------------------------------------------------
  #     addeam
  # ----------------------------------------------------------------------

  addeam:
    mem_mb: 24000
    cpus_per_task: 20
    runtime: 4320
    slurm_partition: "savio4_htc"
    slurm_account:  "co_moilab"

  # ----------------------------------------------------------------------
  #     mpileup
  # ----------------------------------------------------------------------

  mpileup:
    threads: 2
    runtime: 360
    slurm_partition: "savio4_htc"

  # ----------------------------------------------------------------------
  #     merge filtered vcfs
  # ----------------------------------------------------------------------

  merge_filt:
    cpus_per_task: 10
    mem_mb: 91400
    slurm_partition: "savio4_htc"
    runtime: 720

  # ----------------------------------------------------------------------
  #     gbs2ploidy
  # ----------------------------------------------------------------------

  gbs2ploidy:
    cpus_per_task: 1
    mem_mb: 9600
    slurm_partition: "savio4_htc"
    runtime: 720

  # ----------------------------------------------------------------------
  #     updog
  # ----------------------------------------------------------------------

  updog:
    cpus_per_task: 10
    mem_mb: 91400
    runtime: 4320
    slurm_partition: "savio4_htc"

  # ----------------------------------------------------------------------
  #     joint_geno
  # ----------------------------------------------------------------------

  joint_geno:
    mem_mb: 28800
    threads: 3
    runtime: 4320

