# =================================================================================================
#     Input Data
# =================================================================================================

# Set the input data, using absolute file paths (relative paths do not work well with some
# of the snakemake tools we are using in the pipeline, such as shadow directories).
data:

  # Input table that lists all samples with their units and fastq files.
  # Paths in the table need to be absolute! No relative paths (e.g., `../data`)!
  samples: "phillips_samples.tsv"

  reference:

    # Path to the reference genome, using the file ideally as it is provided by the GATK bundle.
    # Path needs to be absolute! No relative path (e.g., `../ref`)!
    genome: "/global/scratch/projects/fc_moilab/PROJECTS/aspen/genome/CAM1604/Populus_tremuloides_var_CAM1604-4_HAP1_V2_release/Populus_tremuloides_var_CAM1604-4/sequences/Populus_tremuloides_var_CAM1604-4_HAP1.mainGenome.fasta"

# =================================================================================================
#    Snakemake settings
# =================================================================================================

max-jobs-per-second: 1
max-status-checks-per-second: 10
#local-cores: 1
latency-wait: 120

# Additional settings used for our purposes
use-conda: True
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True


# =================================================================================================
#     Default Resources
# =================================================================================================
default-resources:
  slurm_partition: "savio3_htc" 
  slurm_account:  "fc_mel"
  runtime: 2880
  cores: 1
  cpus_per_task: 1

# =================================================================================================
#     Tool Parameters
# =================================================================================================

set-resources:

  # ----------------------------------------------------------------------
  #     fastp
  # ----------------------------------------------------------------------
  fastqc:
     threads: 4
        
  # ----------------------------------------------------------------------
  #     fastp
  # ----------------------------------------------------------------------

  # Used only if settings:trimming-tool == fastp
  fastp:
    threads: 4

  # ----------------------------------------------------------------------
  #     bwa-mem2
  # ----------------------------------------------------------------------

  bwa_prep:
    threads: 9
    mem_mb: 80000

  # ----------------------------------------------------------------------
  #     bwa_map
  # ----------------------------------------------------------------------

  # Just under three days to map
  # savio2_htc is 6.4 GB per core
  bwa_map:
    threads: 4
    runtime: 4320
    mem_mb: 25600
    slurm_partition: "savio3_htc"
    #  qos: "savio_long"
    

  # ----------------------------------------------------------------------
  #     samtools_sort
  # ----------------------------------------------------------------------

  samtools_sort:
    mem_mb: 9600
    threads: 1
    runtime: 300

  # ----------------------------------------------------------------------
  #     mark_dups
  # ----------------------------------------------------------------------

  mark_dups:
    mem_mb: 19200
    threads: 2
    runtime: 120

  # ----------------------------------------------------------------------
  #     bamqc
  # ----------------------------------------------------------------------

  bampqc:
    mem_mb: 24000
    threads: 3
    runtime: 120

  # ----------------------------------------------------------------------
  #     mapDamage
  # ----------------------------------------------------------------------

  mapdamage:
    mem_mb: 24000
    threads: 3
    runtime: 120

  # ----------------------------------------------------------------------
  #     gatk
  # ----------------------------------------------------------------------

  # ----------------------------------------------------------------------
  #     snpeff
  # ----------------------------------------------------------------------

  snpeff:
    # Additional parameters for snpeff, see https://pcingola.github.io/SnpEff/se_commandline/
    # Used only if settings:snpeff == true
    extra: "-Xmx4g"

  # ----------------------------------------------------------------------
  #     mapdamage
  # ----------------------------------------------------------------------

  mapdamage:
    # Additional parameters for mapdamage, see http://ginolhac.github.io/mapDamage/
    # Used only if settings:mapdamage == true
    extra: ""

  # ----------------------------------------------------------------------
  #     damageprofiler
  # ----------------------------------------------------------------------

  damageprofiler:
    # Additional parameters for damageprofiler, see https://damageprofiler.readthedocs.io/en/latest/contents/generalUsage.html
    # Used only if settings:damageprofiler == true
    extra: ""

  # ----------------------------------------------------------------------
  #     multiqc
  # ----------------------------------------------------------------------

  multiqc:
    # Additional parameter for multiqc
    extra: ""
